.TH "src/shapes Directory Reference" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shapes Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBintersection\&.h\fP"
.br
.ti -1c
.RI "file \fBshape\&.h\fP"
.br
.ti -1c
.RI "file \fBshape_container\&.h\fP"
.br
.ti -1c
.RI "file \fBsphere\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsphere\&.h\fP"
.br
.in -1c
