.TH "src/materials Directory Reference" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/materials Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdielectric\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdielectric\&.h\fP"
.br
.ti -1c
.RI "file \fBlambertian\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlambertian\&.h\fP"
.br
.ti -1c
.RI "file \fBmaterial\&.h\fP"
.br
.ti -1c
.RI "file \fBmetal\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmetal\&.h\fP"
.br
.in -1c
