.TH "src/utils/fileio.cpp" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/fileio.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'utils\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::expected< std::string, \fBReadFileError\fP > \fButils::readFile\fP (const fs::path &path) noexcept"
.br
.RI "Read a file from the filesystem\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
