.TH "src/ray/interval.h" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ray/interval.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./utils/utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInterval\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
