.TH "src/shapes/intersection.h" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shapes/intersection.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./ray/ray\&.h'\fP
.br
\fC#include '\&.\&./vec3/vec3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIntersection\fP"
.br
.RI "Class representing an intersection between a ray and a shape\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
