.TH "src/materials/lambertian.cpp" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/materials/lambertian.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lambertian\&.h'\fP
.br
\fC#include '\&.\&./shapes/intersection\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
