.TH "src/materials/lambertian.h" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/materials/lambertian.h
.SH SYNOPSIS
.br
.PP
\fC#include 'material\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLambertian\fP"
.br
.RI "Class representing a lambertian material\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
