.TH "Material" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Material \- Class representing the material of a shape\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <material\&.h>\fP
.PP
Inherited by \fBDielectric\fP, \fBLambertian\fP, and \fBMetal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Material\fP ()=default"
.br
.ti -1c
.RI "virtual std::optional< \fBScatterResult\fP > \fBscatter\fP (\fBRay\fP incoming_ray, \fBIntersection\fP intersect) const =0"
.br
.RI "Calculates the color and scattered ray of a given input ray hitting a shape with a certain material\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class representing the material of a shape\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Material::~Material ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::optional< \fBScatterResult\fP > Material::scatter (\fBRay\fP incoming_ray, \fBIntersection\fP intersect) const\fC [pure virtual]\fP"

.PP
Calculates the color and scattered ray of a given input ray hitting a shape with a certain material\&. 
.PP
\fBParameters\fP
.RS 4
\fIincoming_ray\fP the incoming ray 
.br
\fIintersect\fP the intersection between the incoming ray and the shape 
.RE
.PP
\fBReturns\fP
.RS 4
the color and scattered ray on success, otherwise std::nullopt if no scatter could be calculated 
.RE
.PP

.PP
Implemented in \fBDielectric\fP, \fBLambertian\fP, and \fBMetal\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
