.TH "src/materials/material.h" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/materials/material.h
.SH SYNOPSIS
.br
.PP
\fC#include <optional>\fP
.br
\fC#include '\&.\&./ray/ray\&.h'\fP
.br
\fC#include '\&.\&./vec3/vec3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBScatterResult\fP"
.br
.RI "The result of a scatter operation\&. "
.ti -1c
.RI "class \fBMaterial\fP"
.br
.RI "Class representing the material of a shape\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBColor\fP = \fBVec3\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBColor\fP =  \fBVec3\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
