.TH "src/materials/metal.cpp" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/materials/metal.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'metal\&.h'\fP
.br
\fC#include '\&.\&./shapes/intersection\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
