.TH "src/ray/ray.h" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ray/ray.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./vec3/vec3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRay\fP"
.br
.RI "Class representing a ray shot into the scene from a camera\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
