.TH "src/renderer/renderer.h" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/renderer/renderer.h
.SH SYNOPSIS
.br
.PP
\fC#include <camera/Camera\&.h>\fP
.br
\fC#include <shapes/shape_container\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRenderer\fP"
.br
.RI "Class to render an image\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
