.TH "src/shapes/shape_container.h" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shapes/shape_container.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'shape\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShapeContainer\fP"
.br
.RI "Class for storing multiple shapes\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
