.TH "src/shapes/shape.h" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shapes/shape.h
.SH SYNOPSIS
.br
.PP
\fC#include 'intersection\&.h'\fP
.br
\fC#include '\&.\&./ray/ray\&.h'\fP
.br
\fC#include '\&.\&./ray/interval\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShape\fP"
.br
.RI "Abstract class representing a shape\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
