.TH "src/shapes/sphere.h" 3 "raytracing-example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shapes/sphere.h
.SH SYNOPSIS
.br
.PP
\fC#include <optional>\fP
.br
\fC#include '\&.\&./materials/material\&.h'\fP
.br
\fC#include '\&.\&./vec3/vec3\&.h'\fP
.br
\fC#include '\&.\&./ray/ray\&.h'\fP
.br
\fC#include '\&.\&./shapes/shape\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSphere\fP"
.br
.RI "Class representing a spherical object in the scene\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for raytracing-example from the source code\&.
